name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.2.0
        host: linux
        target: desktop

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libtiff-dev libgeotiff-dev cmake

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_PREFIX_PATH=$HOME/Qt/6.2.0/gcc_64

    - name: Build
      run: cmake --build build
